# system
NUM_GPUS: 4
NUM_CPUS: 4

# model
ARCHITECTURE: 'unet_residual_3d' 
FILTERS: [28, 36, 48, 64, 80] 
TARGET_OPT: ['0']
WEIGHT_OPT: [['1']]
LOSS_OPTION: [['WeightedBCE']]
LOSS_WEIGHT: [[1.0]]
IN_PLANES: 1 
OUT_PLANES: 1 
PAD_MODE: 'rep' 
NORM_MODE: 'bn'
ACT_MODE: 'elu'
EMBEDDING: 1
HEAD_DEPTH: 1
INPUT_SIZE: [8, 256, 256]
OUTPUT_SIZE: [8, 256, 256]
REGU_OPT: []
REGU_WEIGHT: []
FINETUNE: ''
EXACT: True
SIZE_MATCH: True
PRE_MODEL: ''
PRE_MODEL_LAYER: ''
PRE_MODEL_ITER: 0
PRE_MODEL_LAYER_SELECT: -1

# dataset
DATA_SCALE: [1., 1., 1.]
SCALE_FACTOR: [2, 3, 3]
IMAGE_NAME: ''
LABEL_NAME: ''
INPUT_PATH: ''
OUTPUT_PATH: ''
PAD_SIZE: [2, 64, 64] 
LABEL_EROSION: 0
LABEL_BINARY: False
LABEL_MAG: 0
DO_CHUNK_TITLE: 0
DATA_CHUNK_NUM: [1, 1, 1]
DATA_CHUNK_NUM_IND: []
DATA_CHUNK_STRIDE: True
DATA_CHUNK_ITER: 1000
DATA_INVALID_THRES: [0., 0.]
PRE_LOAD_DATA: [None,None,None]
REJECT_SIZE_THRES: 100
REJECT_P: 0.95

# augmentation
ROTATE: True
ROTATE_P: 0.1
RESCALE: True
RESCALE_P: 0.5
FLIP: True
FLIP_P: 1.0
FLIP_DO_ZTRANS: 0
ELASTIC: True
ELASTIC_ALPHA: 12.0
ELASTIC_SIGMA: 4.0
ELASTIC_P: 0.75
GRAYSCALE: True
GRAYSCALE_P: 0.75
MISSINGPARTS: True
MISSINGPARTS_P: 0.9
MISSINGSECTION: True
MISSINGSECTION_P: 0.5
MISALIGNMENT: True
MISALIGNMENT_P: 1.0
MISALIGNMENT_DISPLACEMENT: 16

# train
LR_SCHEDULER_NAME: "MultiStepLR"
ITERATION_STEP: 1
ITERATION_SAVE: 5000
ITERATION_TOTAL: 40000
BASE_LR: 0.001
BIAS_LR_FACTOR: 1.0
WEIGHT_DECAY_BIAS: 0.0
MOMENTUM: 0.9
WEIGHT_DECAY: 0.0001
WEIGHT_DECAY_NORM: 0.0
GAMMA: 0.1
STEPS: (30000, 35000)
WARMUP_FACTOR: 1.0 / 1000
WARMUP_ITERS: 1000
WARMUP_METHOD: "linear"
CHECKPOINT_PERIOD: 5000
SAMPLES_PER_BATCH: 16

# monitor
LOG_OPT: [1, 1, 0]
VIS_OPT: [0, 8]
ITERATION_NUM: [10, 50]

# inference
INPUT_SIZE: [8, 256, 256]
OUTPUT_SIZE: [8, 256, 256]
IMAGE_NAME: ''
OUTPUT_PATH: ''
OUTPUT_NAME: 'result.h5'
PAD_SIZE: [8, 64, 64]
STRIDE: [1, 192, 192]
AUG_MODE: 'mean'
AUG_NUM: 4
DO_EVAL: True
DO_3D: True
MODEL_OUTPUT_ID: [None] 
TEST_NUM: 1 
TEST_ID: 0 
SAMPLES_PER_BATCH: 32
